spring.application.name=platzi-market
spring.profiles.active=pdn
server.servlet.context-path=/platzi-market/api
#Se agrega esta linea para poder utilizar el swagger
spring.mvc.pathmatch.matching-strategy = ANT_PATH_MATCHER